/**
 * types/api.ts — wire types mirroring phylanx-api/api/schemas.py.
 *
 * Single source of truth for what the API returns. Generated by hand to
 * keep dependencies minimal (no openapi-typescript build step); the API
 * tests pin the wire shapes so this file drifting is caught by integration
 * tests on the phylanx-api side.
 *
 * Every response carries `_v: 1` (SCHEMA_VERSION); the API may add fields
 * additively without bumping. Renames or removals bump _v and require a
 * client release.
 */

export type AlertTier = "GREEN" | "YELLOW" | "RED";
export type AlertTierCode = 0 | 1 | 2;

export interface HealthResponse {
  _v: 1;
  agent_wallet: string;
  epoch: number;
  score: number;             // 0..1000
  alert_tier: AlertTier;
  alert_tier_code: AlertTierCode;
  flag_set_token?: string;   // opaque token over the raw detection flags
  flag_count?: number;       // number of detectors fired
  flags?: number;            // legacy/mock u32 detection-flag bitset
  immediate_red: boolean;
  signer_count: number;      // how many cluster keys signed this cert
  computed_at: string;       // ISO 8601
}

export interface HistoryEntry {
  epoch: number;
  score: number;
  alert_tier: AlertTier;
  alert_tier_code: AlertTierCode;
  immediate_red: boolean;
  signer_count: number;
  computed_at: string;
}

export interface HistoryResponse {
  _v: 1;
  agent_wallet: string;
  entries: HistoryEntry[];
  from_epoch: number | null;
  to_epoch: number | null;
  limit: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// Diagnosis (Day 34) — Phase-1 off-chain. The `attestation` literal lets
// downstream consumers branch on Phase-1 vs Phase-2 (cert v2) trust.
// ─────────────────────────────────────────────────────────────────────────────

// Phase-1: oracle-emitted, not threshold-signed.
// cert_v2: threshold-signed (Day-38/40 path).
// threshold_attested: evidence-side DA attestation (Day-39).
export type DiagnosisAttestation =
  | "off_chain_v1"
  | "cert_v2"
  | "threshold_attested";

// ─────────────────────────────────────────────────────────────────────────────
// Evidence spans (Day 41) — per-label citations the UI's EvidenceViewer
// expands. Each span has a slot anchor (Solana slot the evaluator
// observed it on) and an optional explorer link. Optional on the wire
// today; rendered only when present so the legacy /diagnosis shape is
// still valid.
// ─────────────────────────────────────────────────────────────────────────────
export interface EvidenceSpan {
  label_bit: number;          // taxonomy bit this span explains
  label_name: string;         // duplicated for offline rendering
  span_index: number;         // ordering within the label's span list
  slot: number;               // Solana slot
  tx_signature: string | null;// nullable when the evidence is observational, not txn
  evidence_kind: "trace" | "trade" | "tool_call" | "model_output";
  summary: string;            // one-line operator-readable
  digest_hex: string;         // sha256 over the span's raw bytes
}

export type LabelEvidenceMap = Record<number, EvidenceSpan[]>; // keyed by label_bit

export type Severity = "INFO" | "LOW" | "MED" | "HIGH" | "CRITICAL";

export interface DimensionBreakdownEntry {
  dimension: string;
  score: number;
  max_score: number;
  score_normalised: number;
  flags: number;
  sub_scores: Record<string, number>;
  algo_version: number;
}

export interface DecodedFlagLabel {
  name: string;
  bit: number;
  description: string;
  severity: Severity;
  owasp_refs: string[];
}

export interface RemediationHint {
  name: string;
  bit: number;
}

export interface DiagnosisResponse {
  _v: 1;
  attestation: DiagnosisAttestation;

  agent_wallet: string;
  epoch: number;
  score: number;
  alert_tier: AlertTier;
  alert_tier_code: AlertTierCode;
  immediate_red: boolean;

  dimensions: DimensionBreakdownEntry[];
  weighted_contributions: Record<string, number>;

  flags: number;
  decoded_labels: DecodedFlagLabel[];
  undecoded_flag_bits: number[];
  remediation_hints: RemediationHint[];
  aggregate_severity: Severity;

  confidence: number;
  gaming_detected: boolean;
  gaming_drop_fraction: number;
  delta_clamped: boolean;

  scoring_algo_version: number;
  scoring_weights_version: number;
  scoring_schema_fingerprint: string;
  baseline_stats_hash: string;

  computed_at: string;

  // Day-41 additions — optional so the legacy diagnosis shape still validates.
  evidence_spans?: EvidenceSpan[];
  applied_remediations?: AppliedRemediation[];
}

// AppliedRemediation: a remediation that was ACTUALLY enacted by the
// operator in a prior epoch, surfaced on the recovering-agent story so
// the panel reads as "here is the remediation history, not a hint".
export interface AppliedRemediation {
  name: string;
  bit: number;
  applied_at_epoch: number;
  applied_at: string; // ISO 8601
  outcome: "in_progress" | "succeeded" | "rolled_back";
  note: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Label deviation events (Day 41 transparency surface) — which oracle
// node disagreed on which label bits in which epoch. This is the
// label-level analogue of the score-level Byzantine flag, and is what
// /transparency newly shows so a partner can see WHERE consensus split.
// ─────────────────────────────────────────────────────────────────────────────
export interface LabelDeviationEvent {
  node: string;
  epoch: number;
  subject_agent: string;
  // Bits the cluster majority believed fired; this node's view
  // diverged — either missing a bit the majority called, or calling a
  // bit the majority dropped.
  majority_bits: number[];
  minority_bits: number[];
  label_names: string[]; // names corresponding to the symmetric difference
  computed_at: string;
}

export interface ByzantineFlagEntry {
  node: string;
  epoch: number;
  subject_agent: string;
  accused_score: number;
  cluster_median: number;
  deviation: number;
}

export interface ByzantineRecentResponse {
  _v: 1;
  flags: ByzantineFlagEntry[];
  since_epoch: number | null;
}

export interface StrikeEntry {
  strikes: number;
  flagged_epochs: number[];
  challenged: boolean;
}

export interface StrikeSummaryResponse {
  _v: 1;
  summary: Record<string, StrikeEntry>;
}

export interface ChallengeEntry {
  challenge_index: number;
  accused_node: string;
  proof_type: number;
  subject_epoch: number;
  subject_agent: string;
  accused_score: number;
  cluster_median: number;
  evidence_hash: string;
  status: "pending" | "upheld" | "dismissed";
  filed_at: number;
}

export interface ChallengesResponse {
  _v: 1;
  accused_node: string;
  challenges: ChallengeEntry[];
}

export interface HeartbeatEntry {
  node: string;
  last_seen_unix: number;
  epoch: number;
}

export interface EpochSummaryEntry {
  epoch: number;
  submitted_count: number;
  agent_count: number;
  verified_nodes: string[];
  byzantine_nodes: string[];
  unreachable_nodes: string[];
  elapsed_seconds: number;
  computed_at: string;
}

export interface ClusterHealthResponse {
  _v: 1;
  heartbeats: HeartbeatEntry[];
  recent_epochs: EpochSummaryEntry[];
}

export interface VersionResponse {
  _v: 1;
  api_version: string;
  scoring_algo_version: string | null;
  scoring_weights_version: string | null;
  network: "localnet" | "devnet" | "testnet" | "mainnet-beta";
  network_is_production: boolean;
}

export interface ApiError {
  error: string;
  detail: string | null;
}
