[toolchain]
anchor_version = "0.30.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
health_oracle      = "EKK2Aj4C9GW8yt4rE2DmYN9A69LFmazGZgfWsFGwuaRN"
certificate_issuer = "4bsGcUKUmvE7JHXEUFwnDYc9ejh4zfpuTuugz1ghMQW7"
slash_authority    = "8hicwiqhYw68MF4pK8ngoDCH875iXHj8xeLCgbsFYq1r"

[programs.devnet]
health_oracle      = "EKK2Aj4C9GW8yt4rE2DmYN9A69LFmazGZgfWsFGwuaRN"
certificate_issuer = "4bsGcUKUmvE7JHXEUFwnDYc9ejh4zfpuTuugz1ghMQW7"
slash_authority    = "8hicwiqhYw68MF4pK8ngoDCH875iXHj8xeLCgbsFYq1r"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet  = "~/.config/solana/id.json"

[scripts]
test = "tsx tests/commit_baseline.integration.ts"
