/**
 * types/api.ts — wire types mirroring helixor-api/api/schemas.py.
 *
 * Single source of truth for what the API returns. Generated by hand to
 * keep dependencies minimal (no openapi-typescript build step); the API
 * tests pin the wire shapes so this file drifting is caught by integration
 * tests on the helixor-api side.
 *
 * Every response carries `_v: 1` (SCHEMA_VERSION); the API may add fields
 * additively without bumping. Renames or removals bump _v and require a
 * client release.
 */

export type AlertTier = "GREEN" | "YELLOW" | "RED";
export type AlertTierCode = 0 | 1 | 2;

export interface HealthResponse {
  _v: 1;
  agent_wallet: string;
  epoch: number;
  score: number;             // 0..1000
  alert_tier: AlertTier;
  alert_tier_code: AlertTierCode;
  flag_set_token?: string;   // opaque token over the raw detection flags
  flag_count?: number;       // number of detectors fired
  flags?: number;            // legacy/mock u32 detection-flag bitset
  immediate_red: boolean;
  signer_count: number;      // how many cluster keys signed this cert
  computed_at: string;       // ISO 8601
}

export interface HistoryEntry {
  epoch: number;
  score: number;
  alert_tier: AlertTier;
  alert_tier_code: AlertTierCode;
  immediate_red: boolean;
  signer_count: number;
  computed_at: string;
}

export interface HistoryResponse {
  _v: 1;
  agent_wallet: string;
  entries: HistoryEntry[];
  from_epoch: number | null;
  to_epoch: number | null;
  limit: number;
}

export interface ByzantineFlagEntry {
  node: string;
  epoch: number;
  subject_agent: string;
  accused_score: number;
  cluster_median: number;
  deviation: number;
}

export interface ByzantineRecentResponse {
  _v: 1;
  flags: ByzantineFlagEntry[];
  since_epoch: number | null;
}

export interface StrikeEntry {
  strikes: number;
  flagged_epochs: number[];
  challenged: boolean;
}

export interface StrikeSummaryResponse {
  _v: 1;
  summary: Record<string, StrikeEntry>;
}

export interface ChallengeEntry {
  challenge_index: number;
  accused_node: string;
  proof_type: number;
  subject_epoch: number;
  subject_agent: string;
  accused_score: number;
  cluster_median: number;
  evidence_hash: string;
  status: "pending" | "upheld" | "dismissed";
  filed_at: number;
}

export interface ChallengesResponse {
  _v: 1;
  accused_node: string;
  challenges: ChallengeEntry[];
}

export interface HeartbeatEntry {
  node: string;
  last_seen_unix: number;
  epoch: number;
}

export interface EpochSummaryEntry {
  epoch: number;
  submitted_count: number;
  agent_count: number;
  verified_nodes: string[];
  byzantine_nodes: string[];
  unreachable_nodes: string[];
  elapsed_seconds: number;
  computed_at: string;
}

export interface ClusterHealthResponse {
  _v: 1;
  heartbeats: HeartbeatEntry[];
  recent_epochs: EpochSummaryEntry[];
}

export interface VersionResponse {
  _v: 1;
  api_version: string;
  scoring_algo_version: string | null;
  scoring_weights_version: string | null;
  network: "localnet" | "devnet" | "testnet" | "mainnet-beta";
  network_is_production: boolean;
}

export interface ApiError {
  error: string;
  detail: string | null;
}
