# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from oracle.proto import cluster_pb2 as cluster__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cluster_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OracleClusterStub(object):
    """-----------------------------------------------------------------------------
    The cluster service.
    -----------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/phylanx.oracle.cluster.v1.OracleCluster/Ping',
                request_serializer=cluster__pb2.PingRequest.SerializeToString,
                response_deserializer=cluster__pb2.PingResponse.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/phylanx.oracle.cluster.v1.OracleCluster/Commit',
                request_serializer=cluster__pb2.CommitRequest.SerializeToString,
                response_deserializer=cluster__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.Reveal = channel.unary_unary(
                '/phylanx.oracle.cluster.v1.OracleCluster/Reveal',
                request_serializer=cluster__pb2.RevealRequest.SerializeToString,
                response_deserializer=cluster__pb2.RevealResponse.FromString,
                _registered_method=True)
        self.GetScores = channel.unary_unary(
                '/phylanx.oracle.cluster.v1.OracleCluster/GetScores',
                request_serializer=cluster__pb2.GetScoresRequest.SerializeToString,
                response_deserializer=cluster__pb2.GetScoresResponse.FromString,
                _registered_method=True)


class OracleClusterServicer(object):
    """-----------------------------------------------------------------------------
    The cluster service.
    -----------------------------------------------------------------------------
    """

    def Ping(self, request, context):
        """Liveness + identity check. Used by the transport to confirm a peer is
        reachable and to exchange node identities.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Phase-1 of commit-reveal: a node sends the HASH of its epoch scores.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reveal(self, request, context):
        """Phase-2 of commit-reveal: a node reveals its actual epoch scores. A
        peer verifies the reveal hashes to the earlier commit.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScores(self, request, context):
        """Day 24: a node fetches a peer's epoch scores, to compute the cluster
        median. Direct score exchange (commit-reveal hardening is a later day).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OracleClusterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=cluster__pb2.PingRequest.FromString,
                    response_serializer=cluster__pb2.PingResponse.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=cluster__pb2.CommitRequest.FromString,
                    response_serializer=cluster__pb2.CommitResponse.SerializeToString,
            ),
            'Reveal': grpc.unary_unary_rpc_method_handler(
                    servicer.Reveal,
                    request_deserializer=cluster__pb2.RevealRequest.FromString,
                    response_serializer=cluster__pb2.RevealResponse.SerializeToString,
            ),
            'GetScores': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScores,
                    request_deserializer=cluster__pb2.GetScoresRequest.FromString,
                    response_serializer=cluster__pb2.GetScoresResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'phylanx.oracle.cluster.v1.OracleCluster', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('phylanx.oracle.cluster.v1.OracleCluster', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OracleCluster(object):
    """-----------------------------------------------------------------------------
    The cluster service.
    -----------------------------------------------------------------------------
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phylanx.oracle.cluster.v1.OracleCluster/Ping',
            cluster__pb2.PingRequest.SerializeToString,
            cluster__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phylanx.oracle.cluster.v1.OracleCluster/Commit',
            cluster__pb2.CommitRequest.SerializeToString,
            cluster__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reveal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phylanx.oracle.cluster.v1.OracleCluster/Reveal',
            cluster__pb2.RevealRequest.SerializeToString,
            cluster__pb2.RevealResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phylanx.oracle.cluster.v1.OracleCluster/GetScores',
            cluster__pb2.GetScoresRequest.SerializeToString,
            cluster__pb2.GetScoresResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
