//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: certificate_issuer
// ----------------------------------------------------------------------------
pub mod certificate_issuer {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for certificate_issuer
    pub fn program_id() -> Pubkey {
        pubkey!("Cert1xor11111111111111111111111111111111111")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: GetCertificate
    // ....................................................................

    /// Main instruction struct for GetCertificate
    pub struct GetCertificateInstruction {
        pub accounts: GetCertificateInstructionAccountMetas,
        pub data: GetCertificateInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for GetCertificate instruction
    #[derive(Debug, Clone, Default)]
    pub struct GetCertificateInstructionAccountMetas {
        pub certificate: AccountMeta,
    }

    /// Account pubkeys for GetCertificate instruction
    #[derive(Debug, Clone)]
    pub struct GetCertificateInstructionAccounts {
        pub certificate: Pubkey,
    }

    impl GetCertificateInstructionAccounts {
        pub fn new(certificate: Pubkey) -> Self {
            Self { certificate }
        }
    }

    /// Instruction data for GetCertificate
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct GetCertificateInstructionData {
        pub agent_wallet: Pubkey,

        pub epoch: u64,
    }

    impl GetCertificateInstructionData {
        pub fn new(agent_wallet: Pubkey, epoch: u64) -> Self {
            Self {
                agent_wallet,

                epoch,
            }
        }
    }

    /// Implementation for GetCertificateInstruction
    impl GetCertificateInstruction {
        fn discriminator() -> [u8; 8] {
            [56u8, 133u8, 43u8, 202u8, 134u8, 127u8, 210u8, 56u8]
        }

        pub fn data(data: GetCertificateInstructionData) -> Self {
            Self {
                accounts: GetCertificateInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: GetCertificateInstructionAccounts) -> Self {
            self.accounts.certificate = AccountMeta::new_readonly(accounts.certificate, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.certificate.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitializeConfig
    // ....................................................................

    /// Main instruction struct for InitializeConfig
    pub struct InitializeConfigInstruction {
        pub accounts: InitializeConfigInstructionAccountMetas,
        pub data: InitializeConfigInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeConfig instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeConfigInstructionAccountMetas {
        pub issuer_config: AccountMeta,

        pub admin: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeConfig instruction
    #[derive(Debug, Clone)]
    pub struct InitializeConfigInstructionAccounts {
        pub issuer_config: Pubkey,

        pub admin: Pubkey,
    }

    impl InitializeConfigInstructionAccounts {
        pub fn new(issuer_config: Pubkey, admin: Pubkey) -> Self {
            Self {
                issuer_config,

                admin,
            }
        }
    }

    /// Instruction data for InitializeConfig
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeConfigInstructionData {
        pub issuer_node: Pubkey,

        pub cluster_keys: Vec<Pubkey>,

        pub threshold: u8,
    }

    impl InitializeConfigInstructionData {
        pub fn new(issuer_node: Pubkey, cluster_keys: Vec<Pubkey>, threshold: u8) -> Self {
            Self {
                issuer_node,

                cluster_keys,

                threshold,
            }
        }
    }

    /// Implementation for InitializeConfigInstruction
    impl InitializeConfigInstruction {
        fn discriminator() -> [u8; 8] {
            [208u8, 127u8, 21u8, 1u8, 194u8, 190u8, 196u8, 70u8]
        }

        pub fn data(data: InitializeConfigInstructionData) -> Self {
            Self {
                accounts: InitializeConfigInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeConfigInstructionAccounts) -> Self {
            self.accounts.issuer_config = AccountMeta::new(accounts.issuer_config, false);

            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.issuer_config.clone());

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: IssueCertificate
    // ....................................................................

    /// Main instruction struct for IssueCertificate
    pub struct IssueCertificateInstruction {
        pub accounts: IssueCertificateInstructionAccountMetas,
        pub data: IssueCertificateInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for IssueCertificate instruction
    #[derive(Debug, Clone, Default)]
    pub struct IssueCertificateInstructionAccountMetas {
        pub baseline_stats: AccountMeta,

        pub certificate: AccountMeta,

        pub issuer_config: AccountMeta,

        pub issuer: AccountMeta,

        pub instructions_sysvar: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for IssueCertificate instruction
    #[derive(Debug, Clone)]
    pub struct IssueCertificateInstructionAccounts {
        pub baseline_stats: Pubkey,

        pub certificate: Pubkey,

        pub issuer_config: Pubkey,

        pub issuer: Pubkey,
    }

    impl IssueCertificateInstructionAccounts {
        pub fn new(
            baseline_stats: Pubkey,

            certificate: Pubkey,

            issuer_config: Pubkey,

            issuer: Pubkey,
        ) -> Self {
            Self {
                baseline_stats,

                certificate,

                issuer_config,

                issuer,
            }
        }
    }

    /// Instruction data for IssueCertificate
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct IssueCertificateInstructionData {
        pub epoch: u64,

        pub score: u16,

        pub alert_tier: u8,

        pub flags: u32,

        pub immediate_red: bool,
    }

    impl IssueCertificateInstructionData {
        pub fn new(
            epoch: u64,

            score: u16,

            alert_tier: u8,

            flags: u32,

            immediate_red: bool,
        ) -> Self {
            Self {
                epoch,

                score,

                alert_tier,

                flags,

                immediate_red,
            }
        }
    }

    /// Implementation for IssueCertificateInstruction
    impl IssueCertificateInstruction {
        fn discriminator() -> [u8; 8] {
            [61u8, 197u8, 55u8, 28u8, 159u8, 18u8, 132u8, 128u8]
        }

        pub fn data(data: IssueCertificateInstructionData) -> Self {
            Self {
                accounts: IssueCertificateInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: IssueCertificateInstructionAccounts) -> Self {
            self.accounts.baseline_stats =
                AccountMeta::new_readonly(accounts.baseline_stats, false);

            self.accounts.certificate = AccountMeta::new(accounts.certificate, false);

            self.accounts.issuer_config = AccountMeta::new_readonly(accounts.issuer_config, false);

            self.accounts.issuer = AccountMeta::new(accounts.issuer, true);

            self.accounts.instructions_sysvar = AccountMeta::new_readonly(
                pubkey!("Sysvar1nstructions1111111111111111111111111"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.baseline_stats.clone());

            metas.push(self.accounts.certificate.clone());

            metas.push(self.accounts.issuer_config.clone());

            metas.push(self.accounts.issuer.clone());

            metas.push(self.accounts.instructions_sysvar.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RecordBaseline
    // ....................................................................

    /// Main instruction struct for RecordBaseline
    pub struct RecordBaselineInstruction {
        pub accounts: RecordBaselineInstructionAccountMetas,
        pub data: RecordBaselineInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RecordBaseline instruction
    #[derive(Debug, Clone, Default)]
    pub struct RecordBaselineInstructionAccountMetas {
        pub baseline_stats: AccountMeta,

        pub issuer_config: AccountMeta,

        pub issuer: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for RecordBaseline instruction
    #[derive(Debug, Clone)]
    pub struct RecordBaselineInstructionAccounts {
        pub baseline_stats: Pubkey,

        pub issuer_config: Pubkey,

        pub issuer: Pubkey,
    }

    impl RecordBaselineInstructionAccounts {
        pub fn new(baseline_stats: Pubkey, issuer_config: Pubkey, issuer: Pubkey) -> Self {
            Self {
                baseline_stats,

                issuer_config,

                issuer,
            }
        }
    }

    /// Instruction data for RecordBaseline
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RecordBaselineInstructionData {
        pub agent_wallet: Pubkey,

        pub baseline_hash: [u8; 32],

        pub baseline_algo_version: u8,

        pub epoch: u64,
    }

    impl RecordBaselineInstructionData {
        pub fn new(
            agent_wallet: Pubkey,

            baseline_hash: [u8; 32],

            baseline_algo_version: u8,

            epoch: u64,
        ) -> Self {
            Self {
                agent_wallet,

                baseline_hash,

                baseline_algo_version,

                epoch,
            }
        }
    }

    /// Implementation for RecordBaselineInstruction
    impl RecordBaselineInstruction {
        fn discriminator() -> [u8; 8] {
            [79u8, 136u8, 252u8, 125u8, 30u8, 2u8, 92u8, 126u8]
        }

        pub fn data(data: RecordBaselineInstructionData) -> Self {
            Self {
                accounts: RecordBaselineInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RecordBaselineInstructionAccounts) -> Self {
            self.accounts.baseline_stats = AccountMeta::new(accounts.baseline_stats, false);

            self.accounts.issuer_config = AccountMeta::new_readonly(accounts.issuer_config, false);

            self.accounts.issuer = AccountMeta::new(accounts.issuer, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.baseline_stats.clone());

            metas.push(self.accounts.issuer_config.clone());

            metas.push(self.accounts.issuer.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: BaselineRecorded
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct BaselineRecorded {
    pub agent_wallet: Pubkey,

    pub baseline_algo_version: u8,

    pub epoch_recorded: u64,

    pub recorder: Pubkey,

    pub recorded_at: i64,
}

impl BaselineRecorded {
    pub fn new(
        agent_wallet: Pubkey,

        baseline_algo_version: u8,

        epoch_recorded: u64,

        recorder: Pubkey,

        recorded_at: i64,
    ) -> Self {
        Self {
            agent_wallet,

            baseline_algo_version,

            epoch_recorded,

            recorder,

            recorded_at,
        }
    }
}

/// Custom struct: BaselineStats
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct BaselineStats {
    pub agent_wallet: Pubkey,

    pub baseline_hash: [u8; 32],

    pub baseline_algo_version: u8,

    pub recorded_at: i64,

    pub recorder: Pubkey,

    pub epoch_recorded: u64,

    pub bump: u8,

    pub layout_version: u8,

    pub _reserved: [u8; 32],
}

impl BaselineStats {
    pub fn new(
        agent_wallet: Pubkey,

        baseline_hash: [u8; 32],

        baseline_algo_version: u8,

        recorded_at: i64,

        recorder: Pubkey,

        epoch_recorded: u64,

        bump: u8,

        layout_version: u8,

        _reserved: [u8; 32],
    ) -> Self {
        Self {
            agent_wallet,

            baseline_hash,

            baseline_algo_version,

            recorded_at,

            recorder,

            epoch_recorded,

            bump,

            layout_version,

            _reserved,
        }
    }
}

/// Custom struct: CertificateIssued
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct CertificateIssued {
    pub agent_wallet: Pubkey,

    pub epoch: u64,

    pub score: u16,

    pub alert_tier: u8,

    pub flags: u32,

    pub immediate_red: bool,

    pub issuer: Pubkey,

    pub issued_at: i64,
}

impl CertificateIssued {
    pub fn new(
        agent_wallet: Pubkey,

        epoch: u64,

        score: u16,

        alert_tier: u8,

        flags: u32,

        immediate_red: bool,

        issuer: Pubkey,

        issued_at: i64,
    ) -> Self {
        Self {
            agent_wallet,

            epoch,

            score,

            alert_tier,

            flags,

            immediate_red,

            issuer,

            issued_at,
        }
    }
}

/// Custom struct: CertificateRead
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct CertificateRead {
    pub agent_wallet: Pubkey,

    pub epoch: u64,

    pub score: u16,

    pub alert_tier: u8,

    pub flags: u32,

    pub immediate_red: bool,

    pub issued_at: i64,
}

impl CertificateRead {
    pub fn new(
        agent_wallet: Pubkey,

        epoch: u64,

        score: u16,

        alert_tier: u8,

        flags: u32,

        immediate_red: bool,

        issued_at: i64,
    ) -> Self {
        Self {
            agent_wallet,

            epoch,

            score,

            alert_tier,

            flags,

            immediate_red,

            issued_at,
        }
    }
}

/// Custom struct: HealthCertificate
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct HealthCertificate {
    pub agent_wallet: Pubkey,

    pub epoch: u64,

    pub score: u16,

    pub alert_tier: u8,

    pub flags: u32,

    pub issued_at: i64,

    pub issuer: Pubkey,

    pub baseline_hash: [u8; 32],

    pub immediate_red: bool,

    pub bump: u8,

    pub layout_version: u8,

    pub _reserved: [u8; 48],
}

impl HealthCertificate {
    pub fn new(
        agent_wallet: Pubkey,

        epoch: u64,

        score: u16,

        alert_tier: u8,

        flags: u32,

        issued_at: i64,

        issuer: Pubkey,

        baseline_hash: [u8; 32],

        immediate_red: bool,

        bump: u8,

        layout_version: u8,

        _reserved: [u8; 48],
    ) -> Self {
        Self {
            agent_wallet,

            epoch,

            score,

            alert_tier,

            flags,

            issued_at,

            issuer,

            baseline_hash,

            immediate_red,

            bump,

            layout_version,

            _reserved,
        }
    }
}

/// Custom struct: IssuerConfig
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct IssuerConfig {
    pub authority: Pubkey,

    pub issuer_node: Pubkey,

    pub cluster_keys: Vec<Pubkey>,

    pub threshold: u8,

    pub bump: u8,
}

impl IssuerConfig {
    pub fn new(
        authority: Pubkey,

        issuer_node: Pubkey,

        cluster_keys: Vec<Pubkey>,

        threshold: u8,

        bump: u8,
    ) -> Self {
        Self {
            authority,

            issuer_node,

            cluster_keys,

            threshold,

            bump,
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
