/**
 * lib/taxonomy.ts — typed view over the imported `taxonomy.json`.
 *
 * `taxonomy.json` is generated by the helixor-oracle `python -m diagnosis`
 * dumper and is the single source of truth for both the on-chain bit
 * layout and the human-meaningful labels. This module ONLY adds types;
 * it does not transform the JSON beyond grouping bits into low-32 /
 * high-32 buckets for rendering.
 *
 * The honesty note that lives on /taxonomy comes from this constant —
 * the low-32 bits are detector-trace bits (carried for backwards
 * compatibility), not full taxonomy entries. Mixing them with the OWASP-
 * aligned high-32 labels would over-represent how "named" the surface
 * really is. The page calls this out so external consumers do not
 * mistake a trace bit for an authoritative diagnosis.
 */

import taxonomyJson from "./taxonomy.json";
import type { Severity } from "@/types/api";

export interface FailureModeEntry {
  name: string;
  bit: number;
  value: number;
  description: string;
  severity: Severity;
  owasp_refs: string[];
  default_remediation: {
    value: number;
    codes: string[];
  };
}

export interface RemediationEntry {
  name: string;
  bit: number;
  value: number;
}

export interface Taxonomy {
  schema_version: number;
  failure_modes: FailureModeEntry[];
  remediation_codes: RemediationEntry[];
}

export const TAXONOMY: Taxonomy = taxonomyJson as Taxonomy;

/**
 * Low-32-bit failure modes are passed through from the legacy detector
 * bitset (helixor-oracle/detection/types.py FlagBit). They are "trace"
 * bits: useful for explaining WHY a score is low but not OWASP-aligned
 * diagnoses. The high-32 bits (`bit >= 32`) are the v1 diagnosis surface.
 */
export const LOW_BIT_CUTOFF = 32;

export function lowBitModes(): FailureModeEntry[] {
  return TAXONOMY.failure_modes.filter((m) => m.bit < LOW_BIT_CUTOFF);
}

export function highBitModes(): FailureModeEntry[] {
  return TAXONOMY.failure_modes.filter((m) => m.bit >= LOW_BIT_CUTOFF);
}

export function failureModeByBit(bit: number): FailureModeEntry | undefined {
  return TAXONOMY.failure_modes.find((m) => m.bit === bit);
}

export function failureModeByName(name: string): FailureModeEntry | undefined {
  return TAXONOMY.failure_modes.find((m) => m.name === name);
}

export function remediationByName(
  name: string,
): RemediationEntry | undefined {
  return TAXONOMY.remediation_codes.find((r) => r.name === name);
}

export const SEVERITY_RANK: Record<Severity, number> = {
  INFO:     0,
  LOW:      1,
  MED:      2,
  HIGH:     3,
  CRITICAL: 4,
};

/** Returns a CSS class for severity. Stays monochrome except the
 *  tier-color border on CRITICAL and HIGH (treated like RED), MED/LOW
 *  use ink shades. */
export function severityClass(severity: Severity): string {
  switch (severity) {
    case "CRITICAL": return "text-tier-red border-tier-red/40 bg-tier-red/[0.08]";
    case "HIGH":     return "text-tier-red border-tier-red/30 bg-tier-red/[0.05]";
    case "MED":      return "text-tier-yellow border-tier-yellow/30 bg-tier-yellow/[0.05]";
    case "LOW":      return "text-ink-10 border-ink-4 bg-ink-2";
    case "INFO":     return "text-ink-9 border-ink-4 bg-ink-2";
  }
}
