// =============================================================================
// phylanx-sdk/src/taxonomy_generated.ts — TS mirror of taxonomy.json.
//
// MIRROR, NOT A FORK. The bit layout (failure-mode and remediation bits)
// is the single source of truth in `phylanx-oracle/diagnosis/taxonomy.json`;
// this file is the TypeScript-typed copy a consumer reads when decoding
// a diagnosis response without a network round-trip. If the oracle adds a
// new failure mode, re-run `scripts/regen_taxonomy.ts` (or copy the JSON
// fields by hand) — both halves are then byte-identical for bit→name
// resolution.
//
// WHY GENERATED, NOT IMPORTED FROM A JSON
// ---------------------------------------
// TypeScript JSON imports either pull the *whole* file (fine here, since
// the taxonomy is small) or require resolveJsonModule on every consumer
// project. Inlining the constant keeps the SDK a single-file import
// surface — a consumer does not need any build config to call
// `failureModeName(bit)` after `npm install @phylanx/sdk`.
// =============================================================================
// AUTOGENERATED FROM phylanx-oracle/diagnosis/taxonomy.json
// Mirror of schema_version below — bump alongside the source JSON.
// =============================================================================

export const TAXONOMY_SCHEMA_VERSION = 1;

export type SeverityName = "INFO" | "LOW" | "MED" | "HIGH" | "CRITICAL";

export interface FailureModeEntry {
  /** Stable taxonomy name — uppercase identifier, e.g. "PROMPT_INJECTION". */
  name:        string;
  /** Bit index in the u64 failure-mode bitmask. */
  bit:         number;
  /** One-line human-readable summary. */
  description: string;
  severity:    SeverityName;
  /** OWASP cross-references, e.g. ["LLM01:2025"]. Empty for non-OWASP modes. */
  owaspRefs:   readonly string[];
}

export interface RemediationEntry {
  name: string;
  bit:  number;
}

// =============================================================================
// Failure modes — high-bit OWASP-aligned diagnoses + the low-bit detector
// trace bits the oracle continues to emit (legacy bitmask compatibility).
// =============================================================================

export const FAILURE_MODES: readonly FailureModeEntry[] = Object.freeze([
  { name: "PROVISIONAL",                  bit:  0, description: "detector ran with thin data — outputs are low confidence",          severity: "INFO",     owaspRefs: [] },
  { name: "INSUFFICIENT_DATA",            bit:  1, description: "detector refused to run; the score is a default placeholder",       severity: "LOW",      owaspRefs: [] },
  { name: "INCOMPATIBLE_INPUT",           bit:  2, description: "baseline or feature vector was rejected by the detector",            severity: "LOW",      owaspRefs: [] },
  { name: "IMMEDIATE_RED",                bit:  3, description: "fast-path RED — composite scorer demands immediate flag",            severity: "CRITICAL", owaspRefs: [] },
  { name: "DEGRADED_BASELINE",            bit:  4, description: "active baseline is provisional — drift readings are weak",           severity: "LOW",      owaspRefs: [] },
  { name: "ENSEMBLE_INCOMPLETE",          bit:  5, description: "VULN-24 — fewer than 3 of 5 detectors fired (evasion suspect)",      severity: "MED",      owaspRefs: [] },
  { name: "DIMENSION_CLAMPED",            bit:  6, description: "per-dimension velocity guard fired (single-detector pump suspect)",  severity: "LOW",      owaspRefs: [] },
  { name: "INPUT_DIVERGENCE",             bit:  7, description: "AW-01 — at least one node's input commitment differed from majority", severity: "MED",      owaspRefs: [] },
  { name: "SOURCE_DISAGREEMENT",          bit: 29, description: "AW-01-EXT — a node saw upstream RPC fleet disagreement",             severity: "MED",      owaspRefs: [] },
  { name: "PROMPT_INJECTION",             bit: 32, description: "user-supplied prompt steered the agent off its declared task",       severity: "HIGH",     owaspRefs: ["LLM01:2025"] },
  { name: "AGENT_GOAL_HIJACK",            bit: 33, description: "agent's declared goal was redefined mid-execution by external input", severity: "CRITICAL", owaspRefs: ["ASI01:2026"] },
  { name: "TOOL_MISUSE",                  bit: 34, description: "tool was invoked with malformed args or outside its declared contract", severity: "HIGH", owaspRefs: ["ASI02:2026"] },
  { name: "TOOL_LOOP",                    bit: 35, description: "tool call repeated past the loop budget (cost + latency runaway)",    severity: "MED",      owaspRefs: ["ASI02:2026"] },
  { name: "EXCESSIVE_AGENCY",             bit: 36, description: "agent exercised authority beyond the operator's declared scope",      severity: "HIGH",     owaspRefs: ["LLM06:2025"] },
  { name: "IDENTITY_PRIVILEGE_ABUSE",     bit: 37, description: "agent assumed or escalated to an identity / role it should not hold", severity: "CRITICAL", owaspRefs: ["ASI03:2026"] },
  { name: "SUPPLY_CHAIN_COMPROMISE",      bit: 38, description: "a dependency, model, or pinned artefact failed integrity verification", severity: "CRITICAL", owaspRefs: ["LLM03:2025", "ASI04:2026"] },
  { name: "UNEXPECTED_CODE_EXECUTION",    bit: 39, description: "agent executed code outside its sandbox or declared interpreter",     severity: "CRITICAL", owaspRefs: ["ASI05:2026"] },
  { name: "MEMORY_POISONING",             bit: 40, description: "stored memory entries contradict baseline distribution — write injection", severity: "HIGH", owaspRefs: ["ASI06:2026"] },
  { name: "CONTEXT_POISONING",            bit: 41, description: "in-session context window was steered by injected retrieved content", severity: "HIGH",     owaspRefs: ["ASI06:2026"] },
  { name: "INSECURE_INTER_AGENT_COMM",    bit: 42, description: "peer-to-peer message lacked authentication or used an untrusted channel", severity: "HIGH", owaspRefs: ["ASI07:2026"] },
  { name: "CASCADING_AGENT_FAILURE",      bit: 43, description: "a peer agent's bad output corrupted this agent's downstream chain",   severity: "HIGH",     owaspRefs: ["ASI08:2026"] },
  { name: "HUMAN_TRUST_EXPLOITATION",     bit: 44, description: "agent output exploited user trust patterns (urgency, authority cues)", severity: "MED",     owaspRefs: ["ASI09:2026"] },
  { name: "ROGUE_AGENT",                  bit: 45, description: "agent acted against its declared principal — full identity divergence", severity: "CRITICAL", owaspRefs: ["ASI10:2026"] },
  { name: "SENSITIVE_INFO_DISCLOSURE",    bit: 46, description: "agent surfaced data outside its declared confidentiality scope",      severity: "HIGH",     owaspRefs: ["LLM02:2025"] },
  { name: "DATA_MODEL_POISONING",         bit: 47, description: "training / fine-tuning artefacts diverged from approved provenance",   severity: "HIGH",     owaspRefs: ["LLM04:2025"] },
  { name: "IMPROPER_OUTPUT_HANDLING",     bit: 48, description: "downstream consumer received insufficiently sanitised agent output",   severity: "MED",      owaspRefs: ["LLM05:2025"] },
  { name: "SYSTEM_PROMPT_LEAK",           bit: 49, description: "internal system prompt or hidden instructions surfaced in output",     severity: "MED",      owaspRefs: ["LLM07:2025"] },
  { name: "VECTOR_EMBEDDING_WEAKNESS",    bit: 50, description: "retrieval / embedding step admitted adversarial or malformed vectors", severity: "MED",      owaspRefs: ["LLM08:2025"] },
  { name: "MISINFORMATION",               bit: 51, description: "output contained factually wrong claims at material rate",             severity: "MED",      owaspRefs: ["LLM09:2025"] },
  { name: "UNBOUNDED_CONSUMPTION",        bit: 52, description: "per-call resource use exceeded declared envelope (tokens, cost, time)", severity: "MED",    owaspRefs: ["LLM10:2025"] },
  { name: "HALLUCINATION_CASCADE",        bit: 53, description: "a hallucinated step in a chain corrupted every dependent downstream step", severity: "HIGH", owaspRefs: [] },
  { name: "OUTPUT_DISTRIBUTION_DRIFT",    bit: 54, description: "output distribution diverged materially from the established baseline", severity: "MED",    owaspRefs: [] },
  { name: "CONTEXT_WINDOW_EXHAUSTION",    bit: 55, description: "context window filled — agent began truncating load-bearing history",  severity: "LOW",      owaspRefs: [] },
  { name: "LATENCY_DEGRADATION",          bit: 56, description: "per-call latency exceeded SLO baseline by sustained margin",           severity: "LOW",      owaspRefs: [] },
  { name: "COST_BLOWUP",                  bit: 57, description: "spend per task exceeded declared budget envelope",                     severity: "MED",      owaspRefs: [] },
  { name: "ALIGNMENT_REGRESSION",         bit: 58, description: "behavioural alignment metrics regressed after a model / config swap",  severity: "HIGH",     owaspRefs: [] },
  { name: "DATA_LEAKAGE",                 bit: 59, description: "training / customer data leaked into outputs against confidentiality policy", severity: "HIGH", owaspRefs: [] },
  { name: "JAILBREAK",                    bit: 60, description: "safety filter bypassed via known or novel jailbreak technique",        severity: "HIGH",     owaspRefs: [] },
  { name: "SUB_AGENT_DEADLOCK",           bit: 61, description: "sub-agents stalled in mutual wait — no forward progress",              severity: "MED",      owaspRefs: [] },
  { name: "ROLE_CONFUSION",               bit: 62, description: "agent confused its declared role with that of a peer or user",         severity: "MED",      owaspRefs: [] },
]);

// =============================================================================
// Remediation codes — the playbook actions a decoded label maps to.
// =============================================================================

export const REMEDIATION_CODES: readonly RemediationEntry[] = Object.freeze([
  { name: "PAUSE_AGENT",              bit:  0 },
  { name: "ISOLATE_AGENT",            bit:  1 },
  { name: "BLOCK_AGENT_PEER",         bit:  2 },
  { name: "QUARANTINE_TOOL_RESULT",   bit:  3 },
  { name: "RESTART_AGENT_SESSION",    bit:  4 },
  { name: "CLEAR_AGENT_MEMORY",       bit:  5 },
  { name: "REVOKE_AGENT_IDENTITY",    bit:  6 },
  { name: "ROTATE_API_KEYS",          bit:  7 },
  { name: "REVIEW_TOOL_PERMISSIONS",  bit:  8 },
  { name: "REDUCE_AUTONOMY",          bit:  9 },
  { name: "DECREASE_RATE_LIMITS",     bit: 10 },
  { name: "INCREASE_RATE_LIMITS",     bit: 11 },
  { name: "PATCH_PROMPT_GUARD",       bit: 12 },
  { name: "ENABLE_OUTPUT_FILTER",     bit: 13 },
  { name: "TIGHTEN_RETRIEVAL_FILTER", bit: 14 },
  { name: "VERIFY_SUPPLY_CHAIN",      bit: 15 },
  { name: "ROLLBACK_MODEL_VERSION",   bit: 16 },
  { name: "RUN_FRESH_BASELINE",       bit: 17 },
  { name: "SCAN_MEMORY_STORE",        bit: 18 },
  { name: "VERIFY_AGENT_IDENTITY",    bit: 19 },
  { name: "ALERT_OPERATORS",          bit: 24 },
  { name: "ENGAGE_HUMAN_REVIEW",      bit: 25 },
  { name: "AUDIT_RECENT_OUTPUTS",     bit: 26 },
  { name: "COLLECT_EVIDENCE",         bit: 27 },
]);

// =============================================================================
// Lookups — keyed maps built once at module load.
// =============================================================================

const FAILURE_BY_BIT  = new Map(FAILURE_MODES.map(m => [m.bit,  m] as const));
const FAILURE_BY_NAME = new Map(FAILURE_MODES.map(m => [m.name, m] as const));
const REMEDIATION_BY_BIT  = new Map(REMEDIATION_CODES.map(r => [r.bit,  r] as const));
const REMEDIATION_BY_NAME = new Map(REMEDIATION_CODES.map(r => [r.name, r] as const));

export function failureModeByBit(bit: number): FailureModeEntry | undefined {
  return FAILURE_BY_BIT.get(bit);
}

export function failureModeByName(name: string): FailureModeEntry | undefined {
  return FAILURE_BY_NAME.get(name);
}

export function failureModeName(bit: number): string | undefined {
  return FAILURE_BY_BIT.get(bit)?.name;
}

export function remediationByBit(bit: number): RemediationEntry | undefined {
  return REMEDIATION_BY_BIT.get(bit);
}

export function remediationByName(name: string): RemediationEntry | undefined {
  return REMEDIATION_BY_NAME.get(name);
}
