// =============================================================================
// consumer-example — Reference DeFi Protocol Integration
//
// This is the canonical example of how a DeFi protocol integrates with
// Helixor on-chain. Real protocols (Kamino, Drift, MarginFi) will use this
// exact pattern.
//
// What this program does:
//   1. Defines a `do_protected_action` instruction that needs a trust check.
//   2. CPIs into health_oracle::get_health() to fetch the agent's TrustScore.
//   3. Reads the returned struct (via Anchor return data plumbing).
//   4. Enforces its own policy: requires score >= MIN_SCORE and is_fresh = true.
//   5. If the policy passes, the action proceeds. Otherwise, it reverts.
//
// Key implementation note — reading CPI return data:
//   Anchor's CpiContext::invoke() returns Result<()>, NOT Result<TrustScore>.
//   To get the return value, we use `program::get_health::CpiReturn` (auto-
//   generated by Anchor) which deserializes from the program's return-data
//   slot via `get_return_data()`.
// =============================================================================

use anchor_lang::prelude::*;
use health_oracle::cpi::accounts::GetHealth;
use health_oracle::cpi::get_health;
use health_oracle::program::HealthOracle;
use health_oracle::state::{AgentRegistration, ScoreSource, TrustScore};

declare_id!("94Gg1gnTZex9mFAJZHB3kLbTiJYYEcRvGTgkArftHJmu");

/// Minimum score this protocol requires to allow a protected action.
/// Real protocols would make this configurable (e.g. governance-controlled).
pub const MIN_TRUST_SCORE: u16 = 600;

#[program]
pub mod consumer_example {
    use super::*;

    /// Demonstrates the full integration flow:
    ///   1. CPI into Helixor's get_health
    ///   2. Read TrustScore from CPI return data
    ///   3. Apply protocol policy (min score + freshness)
    ///   4. Allow or deny the underlying action
    pub fn do_protected_action(ctx: Context<DoProtectedAction>) -> Result<()> {
        // ── 1. Build CPI context ──────────────────────────────────────────────
        let cpi_program = ctx.accounts.health_oracle_program.to_account_info();
        let cpi_accts   = GetHealth {
            querier:             ctx.accounts.caller.to_account_info(),
            agent_registration:  ctx.accounts.agent_registration.to_account_info(),
            trust_certificate:   ctx.accounts.trust_certificate.to_account_info(),
        };
        let cpi_ctx = CpiContext::new(cpi_program, cpi_accts);

        // ── 2. Invoke get_health ──────────────────────────────────────────────
        // The CPI wrapper auto-generated by Anchor returns a struct with a
        // `.get()` method that deserializes the return data.
        let result   = get_health(cpi_ctx)?;
        let score: TrustScore = result.get();

        // ── 3. Apply protocol policy ──────────────────────────────────────────
        // Each protocol's policy is its own decision. Helixor only provides
        // the data — protocols choose how to interpret it.
        require!(
            score.is_fresh,
            ConsumerError::ScoreTooStale,
        );
        require!(
            score.source != ScoreSource::Deactivated,
            ConsumerError::AgentDeactivated,
        );
        require!(
            score.score >= MIN_TRUST_SCORE,
            ConsumerError::ScoreBelowMinimum,
        );
        // Optional: also reject anomaly-flagged agents
        require!(
            !score.anomaly_flag,
            ConsumerError::AgentFlaggedAnomalous,
        );

        msg!(
            "consumer-example: action APPROVED — agent={} score={} source={:?}",
            score.agent,
            score.score,
            score.source,
        );

        // ── 4. Action would proceed here ──────────────────────────────────────
        // In a real protocol: open a margin position, lend USDC, etc.

        Ok(())
    }
}

#[derive(Accounts)]
pub struct DoProtectedAction<'info> {
    /// The user/agent triggering the protected action
    pub caller: Signer<'info>,

    /// The agent whose score gates this action.
    /// CHECK: only used as a pubkey to derive PDAs; not deserialized here.
    pub agent_wallet: UncheckedAccount<'info>,

    /// AgentRegistration PDA — passed through to Helixor
    /// CHECK: validated by Helixor's get_health constraints
    pub agent_registration: UncheckedAccount<'info>,

    /// TrustCertificate PDA — passed through to Helixor
    /// CHECK: validated by Helixor's get_health handler
    pub trust_certificate: UncheckedAccount<'info>,

    /// Helixor's health-oracle program
    pub health_oracle_program: Program<'info, HealthOracle>,
}

#[error_code]
pub enum ConsumerError {
    #[msg("Trust score is below the protocol minimum (600).")]
    ScoreBelowMinimum,
    #[msg("Trust score is stale (>48h). Aborting for safety.")]
    ScoreTooStale,
    #[msg("Agent has been deactivated by its owner.")]
    AgentDeactivated,
    #[msg("Agent is flagged anomalous by Helixor scoring engine.")]
    AgentFlaggedAnomalous,
}
